
development:
  adapter: mysql2
  encoding: utf8
  database: avalanche_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

  
production:
  adapter: mysql
  encoding: utf8
  database: app9986827
  host: instance34127.db.xeround.com.:13388
  username: app9986827
  password: RCzOptiD